travis:
  secure:
    BINSTAR_TOKEN: w6SUm/yijwfSHaO/qUFypQAsedWlS+IWK1VO5ezxIzzJEOhl6KJqeUHXKoNjxlKRCg3/ook6m7Qq7Wp8PmfywcwP5nB7Fa/9gKKh9cynoTBjQ5zMBIZxfDjTCtGD6EdrP1ffvRncikQGgLTQAToqOYRYblWCR6CFERyUTy0yxhg+Cuk7cOhmnRQxvPqvpFlK4PvhKxAAzwtkwWpwi5D5UUeiIfGeW/zYlSz1EnRrIgO+78JLze9pbB2Gn8sSE1qaU147r1rk0Y489XT2Eb5p2VyEPOnk23axc9eUfCDbq06spGPDONAWNtl958Tt7SH7FvlreS4Hp5eqeMY/sWcewAeTXBI62MwWoaf/y26OhV2B9zwg9r/K9AFwRpeuanc7a0VcsjhtJDljWknrKKuQ4tlk9rLFunILORWNokty42g6JdsR0DN0PUth2U+Ct2Cpa/hmGK/1wvry2DQqMqYbO98qIgHVqxoW493UzUPLqpKcU9VwTl7eIVdZnBefCD2N3hlhbpgI0Q5hAvChMSy1DPITGjo0OtTjqNClYeA6CFn51z674IWXCpx7og6InBbp1FaxLz9CTPEfg2orjyKWdOGFR1czMCAh7Xq20WIQsJKuzkb4mlhNtlcruWNpFjD+6kxSc+DCw4B4ecUCMJP1qTqAQI3hVV/1uZ7VI2R7Low=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
